// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// itemsControllerInterface is an autogenerated mock type for the itemsControllerInterface type
type itemsControllerInterface struct {
	mock.Mock
}

// Create provides a mock function with given fields: w, r
func (_m *itemsControllerInterface) Create(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// Get provides a mock function with given fields: w, r
func (_m *itemsControllerInterface) Get(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// Search provides a mock function with given fields: w, r
func (_m *itemsControllerInterface) Search(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}
