// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// usersControllerInterface is an autogenerated mock type for the usersControllerInterface type
type usersControllerInterface struct {
	mock.Mock
}

// Create provides a mock function with given fields: w, r
func (_m *usersControllerInterface) Create(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// Get provides a mock function with given fields: w, r
func (_m *usersControllerInterface) Get(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}
